apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- s3-exposer/flux.yaml
- cert-manager/flux.yaml
- external-dns/flux.yaml
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.48.1/deploy/static/provider/aws/deploy.yaml
patchesStrategicMerge:
- nginx-ingress-configmap.yaml
