apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
  install: {}
  interval: 1m0s
  targetNamespace: external-dns
  values:
    provider: aws
    aws:
      zoneType: public
    source: service
    domainFilters: 
      - tryland.com.es
    txtOwnerId: s3-exposer
    serviceAccount:
      create: false
      name: external-dns

