apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: s3-exposer
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/Daklon/s3-exposer-helm
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: s3-exposer
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./s3-exposer
      sourceRef:
        kind: GitRepository
        name: s3-exposer
  dependsOn:
    - name: cert-manager
  install: {}
  interval: 1m0s
  values:
    deployment:
      access_log: true
      aws_region: eu-west-1
      aws_s3_bucket: my-private-bucket-for-eks
    image:
      repository: pottava/s3-proxy
    ingress:
      annotations:
        cert-manager.io/issuer: letsencrypt
        kubernetes.io/ingress.class: nginx
      className: ""
      enabled: true
      hosts:
      - host: foo.tryland.com.es
        paths:
        - path: /
      tls:
      - hosts:
        - foo.tryland.com.es
        secretName: foo-tls
    issuer:
      email: javierherrera+letsencrypt@posteo.net
      server: https://acme-staging-v02.api.letsencrypt.org/directory
    replicaCount: 1
    secret:
      auth: Zm9vOiRhcHIxJFJVUm1QSC9XJGhWeDdodlA4cGMxWHBpajRENHR1Wi8K

